### PR TITLE
Table Of Contents 2

### PR DESCRIPTION
**Pull request by jhrr**
https://trello.com/c/DvI45DcB/54-as-a-reader-i-can-view-a-stand-alone-toc

- Break up the `App.vue` architecture to handle multiple skeleton-based views.
- Flesh out the basics of a TOC module.
- Add a TOC view and corresponding route logic.

### Related PR
- https://github.com/scaife-viewer/scaife-widgets/pull/18

Screenshot 2020-02-13 19 06 20

### CODE REVIEW

**Comment by jacobwegner** [comment]
[As a reader, I can view a stand alone TOC](https://trello.com/c/DvI45DcB/54-as-a-reader-i-can-view-a-stand-alone-toc)

**Comment by jacobwegner** [comment]
viewable at: https://deploy-preview-8--sv-mini.netlify.com/tocs

**Comment by jhrr** [comment]
@jacobwegner Dead simple `Nav` component added.

**Comment by jtauber** [comment]
Regarding using the skeleton for the "main" TOC view:

I thought we’d eventually get there but hadn’t occurred to me to do it yet
so I think I agree with it but we might still need to smooth out some UX in the future

Library pages can be tackled the same way.

**Pull request merged**
